---
name: Number-Object-Plugin-Tax-AU
abstract: a Number::Object plugin for Australian GST
version: 0.05
author:
  - Matt Koscica <mattk@cpan.org>
license: perl
distribution_type: module
build_requires:
  Number::Object: 0
requires:
  Number::Object: 0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: manually

